project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
    - text: Hands-on Exercises
      menu:
      - text: Hands-on Exercise 1
        href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
      - text: Hands-on Exercise 2
        href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html
      - text: Hands-on Exercise 3a
        href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3a.html
      - text: Hands-on Exercise 3b
        href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3b.html
      - text: Hands-on Exercise 4a
        href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4a.html
      - text: Hands-on Exercise 4b
        href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4b.html
      - text: Hands-on Exercise 4c
        href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4c.html
      - text: Hands-on Exercise 4d
        href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4d.html
      - text: Hands-on Exercise 5a
        href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5a.html
      - text: Hands-on Exercise 5b
        href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5b.html
      - text: Hands-on Exercise 5c
        href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5c.html
      - text: Hands-on Exercise 5d
        href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5d.html
      - text: Hands-on Exercise 5e
        href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5e.html
      - text: Hands-on Exercise 6
        href: Hands-on_Ex/Hands-on_Ex6/Hands-on_Ex6.html
    - text: In-class Exercises
      menu:
      - text: In-class Exercise 1
        href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
      - text: In-class Exercise 6
        href: In-class_Ex/In-class_Ex6/In-class_Ex6.html
    - text: Take-home Exercises
      menu:
      - text: Take-home Exercise 1
        href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
      - text: Take-home Exercise 2
        href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
      - text: Take-home Exercise 3
        href: Take-home_Ex/Take-home_Ex3/Take-home_Ex3.html
    - text: Group Project
      menu:
      - text: nothing here yet
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

