---
title: "In-class Exercise 9"
author: "Michael Berlian"
date: "16 March 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
editor: visual
---

## Getting Started

### Importing package

```{r}
pacman::p_load(igraph, tidygraph, ggraph, visNetwork, lubridate, clock, tidyverse, graphlayouts)
```

### Importing data

```{r}
GAStech_nodes <- read_csv("data/GAStech_email_node.csv")
GAStech_edges <- read_csv("data/GAStech_email_edge-v2.csv")
```

### Data preparation

changing the data into proper type

```{r}
GAStech_edges <- GAStech_edges %>%
  mutate(SendDate = dmy(SentDate)) %>%
  mutate(Weekday = wday(SentDate,
                        label = TRUE,
                        abbr = FALSE))
```

make the counts of email between the source person, target person, and when

filter the source and target person to remove own cc-ed email

```{r}
GAStech_edges_aggregated <- GAStech_edges %>%
  filter(MainSubject == "Work related") %>%
  group_by(source, target, Weekday) %>%
  summarise(Weight = n()) %>%
  filter(source != target) %>%
  filter(Weight > 1) %>%
  ungroup()
```

## Graphing

combining the nodes and edges to make the connection graph

```{r}
GAStech_graph <- tbl_graph(nodes = GAStech_nodes,
                           edges = GAStech_edges_aggregated,
                           directed = TRUE)
```

preview of the graph

```{r}
GAStech_graph
```

graphing

```{r}
ggraph(GAStech_graph) +
  geom_edge_link() +
  geom_node_point()
```

```{r}
g <- ggraph(GAStech_graph) +
  geom_edge_link(aes(colour = 'grey50')) +
  geom_node_point(aes(colour = 'grey40'))

g + theme_graph(background = "grey10",
                text_colour = "white")
```

```{r}
g <-ggraph(GAStech_graph,
           layout = "fr") +
  geom_edge_link(aes()) +
  geom_node_point(aes())

g + theme_graph()
```

```{r}
g <-ggraph(GAStech_graph,
           layout = "nicely") +
  geom_edge_link(aes()) +
  geom_node_point(aes(colour = Department),
                  size = 3)

g + theme_graph()
```

```{r}

g <-ggraph(GAStech_graph,
           layout = "nicely") +
  geom_edge_link(aes(width=Weight),
                 alpha = 0.2) +
  scale_edge_width(range = c(0.1, 5)) + 
  geom_node_point(aes(colour = Department),
                  size = 3)

g + theme_graph()
```

```{r}
set_graph_style()

g <-ggraph(GAStech_graph,
           layout = "nicely") +
  geom_edge_link(aes(width=Weight),
                 alpha = 0.2) +
  scale_edge_width(range = c(0.1, 5)) + 
  geom_node_point(aes(colour = Department),
                  size = 2) 

g + facet_edges(~Weekday)
```

```{r}
g <- GAStech_graph %>%
  mutate(betweenness_centrality = centrality_betweenness()) %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(width = Weight),
                 alpha = 0.2) +
  scale_edge_width(range = c(0.5,1)) +
  geom_node_point(aes(colour = Department,
                      size = betweenness_centrality))

g + theme_graph()
```
